---
- hosts: localhost

  vars_files:
    - vars/tower.yml
    - vars/secret.yml

  tasks:
  - name: Create SSH keys
    openssh_keypair:
      path: "{{ priv_key_filename }}"

  - name: Add Credentials
    awx.awx.tower_credential:
      name: "{{ item.name }}"
      description: "Credentials for cloud based hosts"
      kind: "{{ item.kind }}" 
      organization: "{{ item.organization }}"
      inputs:
        username: "{{ item.username | default(omit) }}"
        ssh_key_data: "{{ item.ssh_key_data | default(omit) }}"
        password: "{{ item.password | default(omit) }}"
      state: present
    loop: "{{ credentials }}"

  - name: Create Inventory for cloud hosts
    awx.awx.tower_inventory:
      name: "{{ inventory.name }}"
      description: "{{ inventory.description }}"
      organization: "{{ inventory.organization }}"
      state: present

  - name: Create Inventory Source for cloud hosts
    awx.awx.tower_inventory_source:
      name: "{{ inventory.name }}-source"
      description: "{{ inventory.description }} source"
      inventory: "{{ inventory.name }}"
      source: "{{ inventory.source }}"
      source_regions: "{{ inventory.region }}"
      credential: "{{ creds_cloud_name }}"
      overwrite: true
      update_on_launch: True
      state: present

  - name: Add Tower Projects
    awx.awx.tower_project:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      organization: "{{ organization }}"
      scm_type: git
      scm_url: "{{ item.scm_url }}"
      scm_branch: "{{ item.scm_branch | default(omit) }}"
      state: present
    loop: "{{ projects }}"

  - name: Add Job Templates
    awx.awx.tower_job_template:
      name: "{{ item.name }}"
      job_type: run
      inventory: "{{ item.inventory }}"
      project: "{{ item.project }}"
      playbook: "{{ item.playbook }}"
      credentials: "{{ item.credentials }}"
      state: present
    loop: "{{ playbooks }}"

  - name: Add Workflow Job Templates
    awx.awx.tower_workflow_job_template:
      name: "{{ workflow_name }}"
      description: "Demo of Workflow Job Template"
      organization: "{{ organization }}"
  
  - name: Create nodes
    awx.awx.tower_workflow_job_template_node:
      identifier: "{{ item.workflow_identifier }}"
      workflow: "{{ workflow_name }}"
      unified_job_template: "{{ item.name }}"
      organization: "{{ organization }}"
    loop: "{{ playbooks }}"
    
  - name: Create Inventory Sync Node
    awx.awx.tower_workflow_job_template_node:
      identifier: Inventory sync
      workflow: "{{ workflow_name }}"
      unified_job_template: "{{ inventory.name }}-source"
      organization: "{{ organization }}"

  # Node assocation phase
  - name: Associate nodes first, sync
    awx.awx.tower_workflow_job_template_node:
      identifier: first
      workflow: "{{ workflow_name }}"
      organization: "{{ organization }}"
      success_nodes: 
        - Inventory sync

  - name: Associate nodes sync, middle
    awx.awx.tower_workflow_job_template_node:
      identifier: Inventory sync
      workflow: "{{ workflow_name }}"
      organization: "{{ organization }}"
      success_nodes: 
        - middle

  - name: Associate nodes middle, end
    awx.awx.tower_workflow_job_template_node:
      identifier: middle
      workflow: "{{ workflow_name }}"
      organization: "{{ organization }}"
      success_nodes: 
        - end
