---
- hosts: localhost

  vars_files:
    - vars/tower.yml
    - vars/secret.yml

  tasks:
  - name: Debug
    debug:
      var: credentials

  - name: Add Credentials
    tower_credential:
      name: "{{ item.name }}"
      description: "Credentials for cloud based hosts"
      kind: "{{ item.kind }}" 
      organization: "{{ item.organization }}"
      username: "{{ item.username | default(omit) }}"
      ssh_key_data: "{{ item.ssh_key_data | default(omit) }}"
      password: "{{ item.password | default(omit) }}"
      state: present
    loop: "{{ credentials }}"

  - name: Add Tower Projects
    tower_project:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      organization: "{{ organization }}"
      scm_type: git
      scm_url: "{{ item.scm_url }}"
      scm_branch: "{{ item.scm_branch | default(omit) }}"
      state: present
    loop: "{{ projects }}"

  - name: Add Job Templates
    tower_job_template:
      name: "{{ item.name }}"
      job_type: run
      inventory: "{{ item.inventory }}"
      project: "{{ item.project }}"
      playbook: "{{ item.playbook }}"
      credential: "{{ item.credentials }}"
      state: present
    loop: "{{ playbooks }}"

  - name: Add Workflow Job Templates
    awx.awx.tower_workflow_job_template:
      name: "DEMO - Workflow"
      description: "Demo of Workflow Job Template"
      organization: "{{ organization }}"
