---
- hosts: localhost

  vars_files:
    - vars/tower.yml

  tasks:
  - name: Create organization
    awx.awx.tower_organization:
      name: "{{ organization }}"
      description: "{{ organization_desc }}"
      state: present

  - name: Add Cloud Org Teams
    awx.awx.tower_team:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      organization: "{{ item.organization }}"
      state: present
    loop: "{{ teams }}"

  - name: Add Cloud Org Users
    awx.awx.tower_user:
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      first_name: "{{ item.first_name }}"
      last_name: "{{ item.last_name }}"
      email: "{{ item.email }}"
      state: present
    loop: "{{ users }}"

  - name: Configure Cloud users roles
    awx.awx.tower_role:
      user: "{{ item.username }}"
      target_team: "{{ item.target_team }}"
      role: "{{ item.role }}"
      state: present
    loop: "{{ users }}"

  - name: Create SSH keys
    openssh_keypair:
      path: "{{ priv_key_filename }}"

  - name: Add Credentials
    awx.awx.credential:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      credential_type: "{{ item.credential_type }}" 
      organization: "{{ item.organization }}"
      inputs: "{{ item.inputs }}"
      state: present
    loop: "{{ credentials }}"
    tags: credentials

  - name: Add Automation Hub credentials
    awx.awx.credential:
      name: Automation Hub Credentials
      description: "Automation Hub Credentials"
      credential_type: "Ansible Galaxy/Automation Hub API Token"
      organization: Default
      inputs:
        url: "{{ automation_hub_url }}"
        auth_url: "{{ automation_hub_sso }}" 
        token: "{{ automation_hub_token }}"  
    tags: automationhub

  - name: Add Automation Hub/Galaxy creds to Cloud org
    awx.awx.organization:
      name: Cloud
      galaxy_credentials:
        - "Automation Hub Credentials"
        - "Ansible Galaxy"
    tags: automationhub

  - name: Create Inventory for cloud hosts
    awx.awx.tower_inventory:
      name: "{{ inventory.name }}"
      description: "{{ inventory.description }}"
      organization: "{{ inventory.organization }}"
      state: present

  - name: Create Inventory Source for cloud hosts
    awx.awx.tower_inventory_source:
      name: "{{ inventory.name }}-source"
      description: "{{ inventory.description }} source"
      inventory: "{{ inventory.name }}"
      source: "{{ inventory.source }}"
      #      source_regions: "{{ inventory.region }}"
      credential: "{{ creds_cloud_name }}"
      overwrite: true
      update_on_launch: True
      source_vars: "{{ inventory.source_vars }}"
      state: present
    tags: inventory_source

  - name: Add Tower Projects
    awx.awx.tower_project:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      organization: "{{ organization }}"
      scm_type: git
      scm_url: "{{ item.scm_url }}"
      scm_branch: "{{ item.scm_branch | default(omit) }}"
      state: present
    loop: "{{ projects }}"

  - name: Add Job Templates
    awx.awx.tower_job_template:
      name: "{{ item.name }}"
      job_type: run
      inventory: "{{ item.inventory }}"
      project: "{{ item.project }}"
      playbook: "{{ item.playbook }}"
      credentials: "{{ item.credentials }}"
      become_enabled: "{{ item.become_enabled | default(omit) }}"
      limit: "{{ item.limit | default(omit) }}"
      extra_vars: "{{ item.extra_vars | default(omit) }}"
      state: present
    loop: "{{ playbooks }}"
    tags: job_templates

  - name: Add Workflow Job Template Basico
    awx.awx.tower_workflow_job_template:
      name: "{{ workflow_name_basico }}"
      description: "Demo of Workflow Job Template"
      organization: "{{ organization }}"
    tags: 
      - job_templates
      - workflows 
      - workflow_basico

  - name: Add Workflow Job Template Avanzado
    awx.awx.tower_workflow_job_template:
      name: "{{ workflow_name_avanzado }}"
      description: "Demo of Workflow Job Template"
      organization: "{{ organization }}"
    tags:
      - job_templates
      - workflows 
      - workflow_avanzado
  
  - name: Create nodes
    awx.awx.tower_workflow_job_template_node:
      identifier: "{{ item.name }}"
      workflow: "{{ item.workflow_name }}"
      unified_job_template: "{{ item.name }}"
      organization: "{{ organization }}"
    loop: "{{ playbooks }}"
    when: item.workflow_identifier is defined
    tags:
      - job_templates
      - workflows 
    
  - name: Create Inventory Sync Node Basico
    awx.awx.tower_workflow_job_template_node:
      identifier: Inventory sync
      workflow: "{{ workflow_name_basico }}"
      unified_job_template: "{{ inventory.name }}-source"
      organization: "{{ organization }}"
    tags: 
      - job_templates
      - workflows
      - workflow_basico

  - name: Create Inventory Sync Node Avanzado
    awx.awx.tower_workflow_job_template_node:
      identifier: Inventory sync Adv
      workflow: "{{ workflow_name_avanzado }}"
      unified_job_template: "{{ inventory.name }}-source"
      organization: "{{ organization }}"
    tags:
      - job_templates
      - workflows
      - workflow_basico

  # Node assocation phase
  - name: Workflow Basico - Associate nodes first, sync
    awx.awx.tower_workflow_job_template_node:
      identifier: "{{ playbooks | json_query(query) }}"
      workflow: "{{ workflow_name_basico }}"
      organization: "{{ organization }}"
      success_nodes: 
        - Inventory sync
    vars:
      query: '[?workflow_name == `{{ workflow_name_basico }}` && workflow_identifier == `first`] | [0].name'
    tags:
      - job_templates
      - workflows
      - workflow_basico

  - name: Workflow Basico - Associate nodes sync, middle
    awx.awx.tower_workflow_job_template_node:
      identifier: Inventory sync
      workflow: "{{ workflow_name_basico }}"
      organization: "{{ organization }}"
      success_nodes: "{{ playbooks | json_query(query) }}"
    vars:
      query: '[?workflow_name == `{{ workflow_name_basico }}` && workflow_identifier == `middle`].name'
    tags:
      - job_templates
      - workflows
      - workflow_basico

  - name: Workflow Basico - Associate nodes middle, end
    awx.awx.tower_workflow_job_template_node:
      identifier: "{{ middle_node }}"
      workflow: "{{ workflow_name_basico }}"
      organization: "{{ organization }}"
      success_nodes: "{{ playbooks | json_query(query) }}"
    vars:
      query: '[?workflow_name == `{{ workflow_name_basico }}` && workflow_identifier == `end`].name'
      middle_query: '[?workflow_name == `{{ workflow_name_basico }}` && workflow_identifier == `middle`] | [0].name'
      middle_node: "{{ playbooks | json_query(middle_query) }}"
    tags:
      - job_templates
      - workflows
      - workflow_basico
      - end

  - name: Workflow Avanzado - Associate nodes first, sync
    awx.awx.tower_workflow_job_template_node:
      identifier: "{{ playbooks | json_query(query) }}"
      workflow: "{{ workflow_name_avanzado }}"
      organization: "{{ organization }}"
      success_nodes: 
        - Inventory sync Adv
    vars:
      query: '[?workflow_name == `{{ workflow_name_avanzado }}` && workflow_identifier == `first_avanzado`] | [0].name'
    tags:
      - job_templates
      - workflows 
      - workflow_avanzado

  - name: Workflow Avanzado - Associate nodes sync, middle
    awx.awx.tower_workflow_job_template_node:
      identifier: Inventory sync Adv
      workflow: "{{ workflow_name_avanzado }}"
      organization: "{{ organization }}"
      success_nodes: "{{ playbooks | json_query(query) }}"
    vars:
      query: '[?workflow_name == `{{ workflow_name_avanzado }}` && workflow_identifier != `first_avanzado`].name'
    tags:
      - job_templates
      - workflows 
      - workflow_avanzado
