---
- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Enable Service
  service:
    name: httpd
    state: started

- name: Setup webpage
  template:
    src: index.j2
    dest: /var/www/html/index.html