---
- name: Provision instance web1
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    assign_public_ip: true
    group: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}" 
    instance_type: t2.micro
    #centos 8.2 image
    image: ami-01ca03df4a6012157
    instance_tags:
      Info: "Provisionado por Ansible"
      Workshop: "{{ ec2_name_prefix }}"
      Name: "{{ ec2_name_prefix }}-web1"
      role: webserver
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
    - device_name: /dev/sda1
      volume_type: gp2
      volume_size: 10 
      delete_on_termination: true
    wait: true
  register: node1_output

- name: Provision instance web2
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    assign_public_ip: true
    group: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}" 
    instance_type: t2.micro
    #centos 8.2 image
    image: ami-01ca03df4a6012157
    instance_tags:
      Info: "Provisionado por Ansible"
      Workshop: "{{ ec2_name_prefix }}"
      Name: "{{ ec2_name_prefix }}-web2"
      role: webserver
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
    - device_name: /dev/sda1
      volume_type: gp2
      volume_size: 10 
      delete_on_termination: true
    wait: true
  register: node2_output

- name: Provision instance lb
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    assign_public_ip: true
    group: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}" 
    instance_type: t2.micro
    #centos 8.2 image
    image: ami-01ca03df4a6012157
    instance_tags:
      Info: "Provisionado por Ansible"
      Workshop: "{{ ec2_name_prefix }}"
      Name: "{{ ec2_name_prefix }}-lb"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
    - device_name: /dev/sda1
      volume_type: gp2
      volume_size: 10 
      delete_on_termination: true
    wait: true
  register: node_output


