---
- name: Provision instance web1
  ec2_instance:
    state: started
    name: "{{ ec2_name_prefix }}-web1"
    key_name: "{{ ec2_name_prefix }}-key"
    network:
      assign_public_ip: true
    security_group: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}" 
    instance_type: t2.micro
    # centos stream 8
    image_id: ami-0ee70e88eed976a1b
    tags:
      Info: "Provisionado por Ansible"
      Workshop: "{{ ec2_name_prefix }}"
      role: webserver
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
    - device_name: /dev/sda1
      ebs:
        volume_type: gp2
        volume_size: 10 
        delete_on_termination: true
    wait: no
  register: node1_output
  async: 1000
  poll: 0  

- name: Provision instance web2
  ec2_instance:
    state: started
    name: "{{ ec2_name_prefix }}-web2"
    key_name: "{{ ec2_name_prefix }}-key"
    network:
      assign_public_ip: true
    security_group: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}" 
    instance_type: t2.micro
    # centos stream 8
    image_id: ami-0ee70e88eed976a1b
    tags:
      Info: "Provisionado por Ansible"
      Workshop: "{{ ec2_name_prefix }}"
      role: webserver
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
    - device_name: /dev/sda1
      ebs:
        volume_type: gp2
        volume_size: 10 
        delete_on_termination: true
    wait: no
  register: node2_output

- name: Provision instance lb
  ec2_instance:
    state: started
    name: "{{ ec2_name_prefix }}-lb"
    key_name: "{{ ec2_name_prefix }}-key"
    network:
      assign_public_ip: true
    security_group: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}" 
    instance_type: t2.micro 
    # centos stream 8
    image_id: ami-0ee70e88eed976a1b
    tags:
      Info: "Provisionado por Ansible"
      Workshop: "{{ ec2_name_prefix }}"
      role: lb
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
    - device_name: /dev/sda1
      ebs:
        volume_type: gp2
        volume_size: 10 
        delete_on_termination: true
    wait: no
  register: lb_node_output

- name: Check async status web1
  async_status: 
    jid: "{{ node1_output.ansible_job_id }}"
  register: node1_job_result
  until: node1_job_result.instances[0].public_ip_address is defined
  retries: 100
  delay: 10

- name: Check async status web2
  async_status: 
    jid: "{{ node2_output.ansible_job_id }}"
  register: node2_job_result
  until: node2_job_result.instances[0].public_ip_address is defined
  retries: 100
  delay: 10

- name: Check async status lb
  async_status: 
    jid: "{{ lb_output.ansible_job_id }}"
  register: node1_job_result
  until: lb_job_result.instances[0].public_ip_address is defined
  retries: 100
  delay: 10

- name: Group DNS info from instances
  set_fact:
    dns_records:
    - dns_name: "lb-{{ ec2_name_prefix }}.{{ dns_zone }}"
      public_ip: "{{ lb_node_output.instances[0].public_ip_address }}"
    - dns_name: "web1-{{ ec2_name_prefix }}.{{ dns_zone }}"
      public_ip: "{{ node1_output.instances[0].public_ip_address }}"
    - dns_name: "web2-{{ ec2_name_prefix }}.{{ dns_zone }}"
      public_ip: "{{ node2_output.instances[0].public_ip_address }}"

- name: Create DNS Records
  route53:
    state: present
    zone: "{{ dns_zone }}"
    record: "{{ item.dns_name }}"
    type: A
    ttl: 60
    value: "{{ item.public_ip }}"
    overwrite: yes
    wait: yes
  loop: "{{ dns_records }}"

- name: Add new instances to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
    ansible_user: centos
  loop: "{{ dns_records }}"

